# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34c2cb7115b748f57359782b743d2de3ddd09d17c2d66779156abe4b5c7dcf642bd19c78e5d6d7e581753e77ff431e8db503e75cc1dda58dde68d0a608239bad

test:
  secret_key_base: b7e18d72634c7f9f9f9a2c85203702fd884af7f3c5bafcd34e75b01bc93ef481a648958788d76b40a9e0679db973ceaf51c08c964fa6ac99e279b51a1a4a3cdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
